### PR TITLE
Remove README references to infix cons operator

### PR DESCRIPTION
**Pull request by bobwhitelock**
This no longer exists as of 4.0.0. Thanks :slightly_smiling_face:

### CODE REVIEW

**Comment by mgold** [comment]
Thank you! ~~Two~~ Three things:
1. The first example should be `cons 4 one`.
2. I've pushed a commit to master that fixes travis. Can you rebase or merge that please?
3. Please add `"./README.md"` to the `tests` array in `tests/elm-verify-examples.json`. This will generate failing tests because of `:::`, which should be fixed by concern 1.

**Comment by bobwhitelock** [comment]
1. Whoops, should've read that better; I've amended the commit to fix it.
2. Sure, rebased.
3. Done :slightly_smiling_face:.

**Comment by mgold** [comment]
Awesome, thanks!

**Comment by mgold** [comment]
4.0.1 released.

**Pull request merged**
